name: CI Laravel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: laravel_test
          MYSQL_DATABASE: caritas
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -u root -plaravel_ci -e "SHOW DATABASES"; do
            sleep 1
          done

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run Sseeders
        run: php artisan db:seed

      - name: Run tests
        run: php artisan test
