name: Deploy Laravel API to Azure

on:
  push:
    branches:
    - main # Ou a branch que você deseja monitorar para deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar PHP e extensões necessárias
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Versão do PHP compatível com o Laravel
        extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml
        coverage: none

    # Instalar dependências do Composer
    - name: Install dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    # Configurar variáveis de ambiente para produção
    - name: Set environment
      run: |
        cp .env.example .env
        php artisan key:generate
      env:
        APP_ENV: production
        APP_DEBUG: false
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    # Publicar para o Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    # Limpar cache do Laravel
    - name: Clear cache
      run: php artisan config:clear && php artisan route:clear && php artisan view:clear
